name: Testes Backend com Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar o Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permissão ao Gradle
        working-directory: back-end
        run: chmod +x gradlew

      - name: Rodar testes
        working-directory: back-end
        run: ./gradlew test
